version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:3.5
  volumes:
    - ./notebooks:/opt/notebooks
  networks:
    - jupyter-network

services:
  jupyterlab:
    build:
      dockerfile: Dockerfile
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/workspace/notebooks
    networks:
      - jupyter-network

  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL= spark://spark-master:7077

networks:
  jupyter-network: